name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: build
        env:
          BASE_PATH: '/FlipFusion'
        run: |
          pnpm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          # this should match the `output` directory in your adapter-static options
          name: build
          path: build/

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages